spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  main:
    allow-circular-references: true
  security:
    user:
      name: dupuids
      password: tshibanda
      roles: manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://host.docker.internal:3306/webservice'
    username: alexandre
    password: bukasa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect

server:
  port: 8761